### ISSUE TITLE
CurseForge Error on opening

### ISSUE THREAD

**Issue by Aleph-byte** [Wesley1808/ServerCore#109]
**Describe the bug**
FTB_SKIES while opening game opens error window

**Reproduce**
Steps to reproduce the behavior:Launch game again

**Expected behavior**
A clear description of what you expected to happen.

NO ERROR MESSAGE

**Versions** -Latest is not a version!
1.19.2 FORGE LAST VERSION FTB SKIES EXPERT 1.9.0
ServerCore:
Minecraft:

**Mod incompatibilities**
List any installed mods you think might play a role in causing this bug.
SERVERCORE

Mod File: /C:/Users/user/AppData/Roaming/.minecraft/modpacks/New Folder/mods/servercore-forge-1.3.5+1.19.2.jar
	Failure message: ServerCore (servercore) has failed to load correctly
		java.lang.IllegalArgumentException: No enum constant me.wesley1808.servercore.common.dynamic.DynamicSetting.CHUNK_TİCK_DİSTANCE
	Mod Version: 1.3.5+1.19.2
	Mod Issue URL: https://github.com/Wesley1808/ServerCore/issues
	Exception message: java.lang.IllegalArgumentException: No enum

**Comment by Wesley1808** [comment]
Try changing the following the config file (config/servercore.toml)
`setting_order = ["chunk_tick_distance", "mobcap_multiplier", "simulation_distance", "view_distance"]` ->
`setting_order = ["CHUNK_TICK_DISTANCE", "MOBCAP_MULTIPLIER", "SIMULATION_DISTANCE", "VIEW_DISTANCE"]`

This should already be fixed in recent versions of the mod but back then I would automatically uppercase the characters if the setting was specified in lowercase, which in some specific languages can change some of the characters to something it doesn't understand, such as `İ`.

**Comment by Puddichim** [comment]
> Try changing the following in the config file (config/servercore.toml) `setting_order = ["chunk_tick_distance", "mobcap_multiplier", "simulation_distance", "view_distance"]` -> `setting_order = ["CHUNK_TICK_DISTANCE", "MOBCAP_MULTIPLIER", "SIMULATION_DISTANCE", "VIEW_DISTANCE"]`
> 
> This should already be fixed in recent versions of the mod but back then I would automatically uppercase the characters if the setting was specified in lowercase (forgetting to specify locale), which in some specific languages can change some of the characters to something it doesn't understand, such as `İ`.

Unfortunately, that change didn't fix my issue; I'm still getting the same error. I wanted to replace the mod folder with recent versions, but I saw that the version 1.19.2 of the mod was last updated on April 12, 2023, on the CurseForge site. What should I do?

**Comment by Wesley1808** [comment]
Could try downloading the build from [this actions run](https://github.com/Wesley1808/ServerCore/actions/runs/10249794573/job/28353986137) (when it finishes building) to see if it works with that?

**Comment by Puddichim** [comment]
I switched my PC's language to English and it solved the problem 🤠

**Comment by Wesley1808** [comment]
The version with the fix for this issue is now released on curseforge and modrinth as 1.3.6+1.19.2
